### ISSUE TITLE
(style) columns width

### ISSUE THREAD

**Issue by cindrikj** [netceteragroup/ngrx-data-grid#25]
- Add option to set the initial width of the columns. Use the configuration of the columns to set the width. 
Currently, the configuration for a single column has the following structure:
`
{
      headerName: 'age',
      field: 'age',
      component: NumberComponent,
      visible: true,
      sortAvailable: true,
      filterAvailable: true,
      filter: {
        filterType: FilterType.Number
      }
}
`
We need to add additional "width" property.
- Set the width only to the columns for which we have passed the "width" property. The rest of the columns should take available space.

**Comment by velinovskav** [comment]
Fixed with: https://github.com/netceteragroup/ngrx-data-grid/pull/33
