### ISSUE TITLE
Pass custom data to the filter component

### ISSUE THREAD

**Issue by xindexer** [netceteragroup/ngrx-data-grid#69]
I have a custom filter for just about every column, right now I have to create a new component for each column, if I could pass a custom variable to the component, I would be able to use one component instead of 20. This is what I currently have: 

`{
      headerName: 'State',
      field: 'state',
      visible: true,
      sortAvailable: true,
      filterAvailable: true,
      filter: {
        component: StateFilterComponent,
      },`

this is what I would like to have

`{
      headerName: 'State',
      field: 'state',
      visible: true,
      sortAvailable: true,
      filterAvailable: true,
      filter: {
        component: MyFilterComponent,
        type: 'state'
      },`

I spent the last few hours trying to extend or modify the module to no avail

**Comment by hdimitrieski** [comment]
Hi @xindexer,

That's actually a good idea. We will add support for passing props inside the custom components.
