### ISSUE TITLE
Add or delete rows

### ISSUE THREAD

**Issue by xindexer** [netceteragroup/ngrx-data-grid#75]
In the data-grid-payload.d.ts file you have 

`export interface UpdateGridDataPayload extends BaseGridPayload {
    shouldUpdate: ShouldUpdateGridElement;
    update: UpdateGridElement;
}`

but there is no mention of add or delete. Is there a way to add or delete a row using that update function?

**Comment by hdimitrieski** [comment]
Hi @xindexer,

No, currently there is no way do delete or add a row. We are working on this feature at the moment. We will have this in the next release.
