### ISSUE TITLE
Pass prop to component

### ISSUE THREAD

**Issue by xindexer** [netceteragroup/ngrx-data-grid#78]
The implementation of passing a prop to the filter component is very useful, what about doing the same to the cell component? 

```
{
headerName: 'Name',
field: 'name',
visible: true,
sortAvailable: true,
filterAvailable: true,
filter: {
        component: NameFilterComponent,
        props: {
          firstOption: 'First Option'
        }
},
component: {
     component: NameComponent,
     props: {
       secondOption: 'Second Option',
      rowIndex: rowIndex
     }
}
```

Edited to add in the rowIndex variable. I would also like that variable to be exposed in the setup so that I can delete the row from a component command. Right now I'm having to subscribe to the store grid variable and then run a ramda command to find the index.

```
this.store.pipe(select(getGridState)).pipe(
    take(1),
    select(getGridData, {gridName: 'doralGrid'}))
.subscribe(results => {
    this.store.dispatch(deleteRow({
        name: this.gridName,
        rowIndex: R.findIndex(R.propEq('id', Number(this.data)))(results)
    }));
});
```
this works but it's a hack

**Comment by hdimitrieski** [comment]
Hi @xindexer,

We will add support for passing props in the cell component in the next release.

And to delete a row there are two options at the moment. The first one is to pass the rowIndex in the action and the corresponding row will be deleted. And the second one is to pass a predicate in the action:
```
this.store.dispatch(deleteRow({
  name: this.gridName,
  where: dataItem => dataItem.id === this.data.id
}));
```
Can you check if this helps?

**Comment by xindexer** [comment]
yes - that is actually a cleaner approach than pushing the rowIndex to my custom component - thank you. I have the add and delete row working in my setup as well, thank you for building this great tool!!

**Comment by xindexer** [comment]
The deleteRow action is not deleting the row using the code you have shown above.

**Comment by velinovskav** [comment]
The feature is implemented.
