### ISSUE TITLE
DeleteRow using dataitem.id is not working

### ISSUE THREAD

**Issue by xindexer** [netceteragroup/ngrx-data-grid#81]
I just updated to 1.14.1

This code will delete the row in the grid

```
this.store.pipe(select(getGridState)).pipe(
take(1),
select(getGridData, {gridName: 'doralGrid'}))
.subscribe(results => {
    this.store.dispatch(deleteRow({
        name: this.gridName,
        rowIndex: R.findIndex(R.propEq('id', Number(this.dataId)))(results)
    }));
});
```

but this code does not work

```
this.store.dispatch(deleteRow({
    name: this.gridName,
    where: dataItem => dataItem.id === this.dataId
}));
````

**Comment by hdimitrieski** [comment]
Hi @xindexer, could it be that the types of thos.dataId and dataItem.id are different? Because as I can notice in your first example the value of this.dataId is converted to to Number and in your second example it isn’t.

**Comment by xindexer** [comment]
That was it, didn't think about the type being different
